### ISSUE TITLE
App Crashing in some devices

### ISSUE THREAD

**Issue by dijialphalab** [uerceg/play-install-referrer-react-native#1]
**Describe the bug**
Devices -  POCO F1,  vivo 1718, OnePlus5
I am using in react native. react-native-play-install-referrer

Fatal Exception: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
       at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:25)
       at com.ugi.play_install_referrer.PlayInstallReferrer$1.onInstallReferrerSetupFinished(PlayInstallReferrer.java:75)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:5)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1956)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1988)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7520)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Environment**
Please describe your working environment:
- **react-native-play-install-referrer** plugin version [e.g. v1.1.4].
- React Native version [e.g. react-native-cli: 2.0.1, react-native: 0.63.0].
-  POCO F1,  vivo 1718, OnePlus5

**Comment by ugi** [comment]
Hi @dijialphalab 

Thanks for reporting this. Seems like the problem might be that for some reason callback method you are defining in your app attempts to be triggered multiple times from native layer which doesn't seem to be allowed in React Native. More information can be found in here:

- https://github.com/facebook/react-native/issues/13595
- https://stackoverflow.com/questions/46065958/react-native-callback-type-only-permits-a-single-invocation-from-native-code
- https://medium.com/nycdev/calling-a-callback-multiple-times-in-a-react-native-module-5c3c61f2fca4

In accordance to advices from resources from above, I have changed the plugin to use native event emitter approach instead of directly passing callback to native layer to be invoked. Hopefully it will solve these crashes.

Please, give latest plugin [v1.1.5](https://www.npmjs.com/package/react-native-play-install-referrer) update a shot and lemme know if that version fixed the issue.

Cheers

**Comment by uerceg** [comment]
Closing this one due to inactivity.

@dijialphalab In case there's need, feel free to comment/reopen.

Cheers
